import os
import cv2
import numpy as np
import util
import matplotlib.pyplot as plt
from morphology.filter_factory import FilterFactory
from morphology.connected_components import CV2ConnectedComponentsGenerator, ConnectedComponents
from ndvi.naip_processor import NAIPProcessor
from web_scraper.imagery_wayback_driver import ImageryWaybackDriver
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from Inferencer.deep_recognizer import DeepGreenSpaceRecognizer


def create_cache():
    util.create_directory(util.NAIP_RANDOM_SAMPLES_DIR)
    util.create_directory(util.WAYBACK_SCREENSHOTS_DIR)
    util.create_directory(util.GROUND_TRUTH_MASKS_DIR)
    util.create_directory(util.GROUND_TRUTH_IMAGES_DIR)


def clean_cache():
    util.remove_all_files(util.NAIP_RANDOM_SAMPLES_DIR)
    util.remove_all_files(util.WAYBACK_SCREENSHOTS_DIR)
    util.remove_all_files(util.GROUND_TRUTH_MASKS_DIR)
    util.remove_all_files(util.GROUND_TRUTH_IMAGES_DIR)


def generate_sample_ground_truth(config_path, checkpoint_path, naip_img_path, n_samples_xy=(2, 2), wayback_scale=18):
    # Create a NAIP processor
    naip_img = util.read_naip_image(naip_img_path)
    naip = NAIPProcessor(naip_img)
    naip_resolution = abs(naip.get_resolution()[0])
    naip_bgr = naip.get_bgr_naip()

    # Initialize Selenium driver
    options = Options()
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.binary_location = util.SELENIUM_DRIVER_BINARY_LOC

    # Get a screenshot of the region of interest
    naip_h, naip_w = naip_bgr.shape[:2]
    wayback_resolution = util.WAYBACK_SCALE_TO_RESOLUTION[str(wayback_scale)]

    naip_sample_xy = util.get_naip_imagery_samples(naip_h, naip_w, n_samples_xy, seed=9527)
    n_digits = naip_sample_xy.shape[0]
    np.save("./cache/naip_random_sample_coordinates.npy", naip_sample_xy)

    # Initialize DeepGreen model
    deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)

    for i, diagonal_xy in enumerate(naip_sample_xy):
        s_h = diagonal_xy[3] - diagonal_xy[1]
        s_w = diagonal_xy[2] - diagonal_xy[0]
        center_r, center_c = diagonal_xy[1] + (s_h // 2 - 1), diagonal_xy[0] + (s_w // 2 - 1)
        print(f"Center {i + 1}: {center_r}, {center_c}")
        naip_sample_img = naip.naip_img[:, diagonal_xy[1]:diagonal_xy[3], diagonal_xy[0]:diagonal_xy[2]]  # naip.reproject("EPSG:4326")
        sample_bgr_img = util.naip_to_bgr(naip_sample_img)
        cv2.imwrite(os.path.join(util.NAIP_RANDOM_SAMPLES_DIR, f"sample_{i + 1}.png"), sample_bgr_img)

        # Get center coordinates of current sample
        center_lon, center_lat = naip.get_lon_lat(row=center_r, col=center_c)
        print(f"Center Geo {i + 1}: {center_lon}, {center_lat}")

        wayback_h, wayback_w = util.get_wayback_shot_size((s_h, s_w), naip_resolution, wayback_resolution)
        driver = webdriver.Chrome(options=options)
        wayback_driver = ImageryWaybackDriver(driver)

        # Load webpage with url
        url = wayback_driver.make_url(center_lon, center_lat, scale=wayback_scale)
        wayback_driver.load_url(url)
        wayback_driver.toggle_off_version_filter()
        wayback_driver.accept_cookies()

        save_wayback = os.path.join(util.WAYBACK_SCREENSHOTS_DIR, f"wayback_shot_{i + 1}.png")
        wayback_img = wayback_driver.take_screenshot(wayback_w, wayback_h,
                                                     save_to_file=save_wayback)
        wayback_img = cv2.cvtColor(wayback_img, cv2.COLOR_RGB2BGR)

        # Get inference from the DeepGreen model
        ground_truth_segs = deep_green.infer_batch([wayback_img])

        # Threshold the segmentation results generated by the DeepGreen model
        _, ground_truth_seg = cv2.threshold(ground_truth_segs[0], 0, 255, cv2.THRESH_BINARY)
        ground_truth_gray = ground_truth_seg.astype(np.uint8)
        ground_truth_color = NAIPProcessor.set_mask_color(ground_truth_gray, (0, 0, 255))
        combined_ground_truth = cv2.addWeighted(wayback_img, 1, ground_truth_color, 0.5, 0)
        cv2.imwrite(os.path.join(util.GROUND_TRUTH_MASKS_DIR, f"ground_truth_mask_{str(i).zfill(n_digits)}.png"),
                    ground_truth_gray)
        cv2.imwrite(os.path.join(util.GROUND_TRUTH_IMAGES_DIR, f"ground_truth_image_{str(i).zfill(n_digits)}.png"),
                    combined_ground_truth)


def generate_ground_truth(input_dir, config_path, checkpoint_path):
    try:
        with os.scandir(input_dir) as entries:
            sorted_entries = sorted(entries, key=lambda x: x.name)
    except OSError as err:
        print(err)

    images = []
    for i, entry in enumerate(sorted_entries):
        if entry.is_file():
            images.append(cv2.imread(entry.path))

    deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)
    n_digits = len(str(len(images)))
    for i, image in enumerate(images):
        ground_truth_seg = deep_green.infer_batch([image])[0]
        _, ground_truth_gray = cv2.threshold(ground_truth_seg, 0, 255, cv2.THRESH_BINARY)
        ground_truth_gray = ground_truth_gray.astype(np.uint8)
        ground_truth_color = NAIPProcessor.set_mask_color(ground_truth_gray, (0, 0, 255))
        combined_ground_truth = cv2.addWeighted(image, 1, ground_truth_color, 0.5, 0)
        cv2.imwrite(os.path.join("./cache/ground_truth_masks/", f"ground_truth_mask_{str(i).zfill(n_digits)}.png"), ground_truth_gray)
        cv2.imwrite(os.path.join("./cache/ground_truth_images/", f"ground_truth_image_{str(i).zfill(n_digits)}.png"), combined_ground_truth)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    # Set model configuration path and checkpoint path
    config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    checkpoint_path = "./checkpoints/iter_1000.pth"
    naip_img_path = "./image/m_4111118_nw_12_060_20210813.tif"

    create_cache()
    clean_cache()
    generate_sample_ground_truth(config_path, checkpoint_path, naip_img_path)

    # main(config_path, checkpoint_path, naip_img_path, n_samples_xy=(8, 10))
    #
    # img_path = "./cache/naip_split"
    # config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    # checkpoint_path = "./checkpoints/iter_1000.pth"
    # output_dir = "./cache/ground_truth_masks"
    #
    # generate_ground_truth(img_path, config_path, checkpoint_path)
    #
    # stitch_in_dir = "./cache/ground_truth_masks/"
    # stitch_out_dir = "./cache/ground_truth_stitched_mask/"
    # util.stitch_images(stitch_in_dir, stitch_out_dir)

    # stitch_in_dir = "./cache/ground_truth_images/"
    # stitch_out_dir = "./cache/ground_truth_stitched_image/"
    # util.stitch_images(stitch_in_dir, stitch_out_dir)

