import json
import os
import cv2
import numpy
import numpy as np
from naip.naip_imagery import NAIPImagery
from web_scraper.imagery_wayback_driver import ImageryWaybackDriver
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from Inference.deep_recognizer import DeepGreenSpaceRecognizer
from naip.naip_sampler import NaipSampler
from utility.image_block import ImageBlock
from utility import util
from naip.sample_method import GridSample


# NAIP_RANDOM_SAMPLES_DIR = "./cache/naip_random_samples/"
# NAIP_RANDOM_SAMPLES_MASKS_DIR = "./cache/naip_random_samples_masks/"
# WAYBACK_SCREENSHOTS_DIR = "./cache/wayback_screenshots/"
# GROUND_TRUTH_MASKS_DIR = "./cache/ground_truth_masks/"
# GROUND_TRUTH_IMAGES_DIR = "./cache/ground_truth_images/"


def create_cache():
    util.create_directory(util.WAYBACK_SCREENSHOTS_DIR)
    util.create_directory(util.NAIP_RANDOM_SAMPLES_DIR)
    util.create_directory(util.NAIP_SAMPLE_MASKS_DIR)
    util.create_directory(util.GROUND_TRUTH_MASKS_DIR)
    util.create_directory(util.GROUND_TRUTH_IMAGES_DIR)


def clean_cache():
    util.remove_all_files(util.WAYBACK_SCREENSHOTS_DIR)
    util.remove_all_files(util.NAIP_RANDOM_SAMPLES_DIR)
    util.remove_all_files(util.NAIP_SAMPLE_MASKS_DIR)
    util.remove_all_files(util.GROUND_TRUTH_MASKS_DIR)
    util.remove_all_files(util.GROUND_TRUTH_IMAGES_DIR)


# def generate_sample_ground_truth(config_path, checkpoint_path, naip_img_path, wayback_scale=18):
#     # Create a NAIP processor
#     naip_img = util.read_naip_image(naip_img_path)
#     naip = NAIPImagery(naip_img)
#     naip_bgr = naip.get_bgr_naip()
#
#     # Initialize Selenium driver
#     options = Options()
#     options.add_experimental_option("excludeSwitches", ["enable-automation"])
#     # options.binary_location = util.SELENIUM_DRIVER_BINARY_LOC
#
#     # Get NAIP size and resolution
#     naip_h, naip_w = naip_bgr.shape[:2]
#     naip_resolution = abs(naip.get_resolution()[0])
#
#     # Get Wayback resolution
#     wayback_resolution = util.WAYBACK_SCALE_TO_RESOLUTION[str(wayback_scale)]
#
#     # naip_sample_xy = utility.get_random_naip_imagery_samples(naip_h, naip_w, n_samples_xy, seed=9527)
#     naip_sampler = NaipSampler(naip_h, naip_w)
#     naip_sample_xy = naip_sampler.get_grid_samples()
#     print(f"Number of sample blocks: {naip_sampler.get_num_of_samples()}")
#     n_digits = len(str(naip_sampler.get_num_of_samples()))
#     # print(f"Number of digits: {n_digits}")
#     np.save("./cache/naip_random_sample_coordinates.npy", naip_sample_xy)
#
#     # Initialize DeepGreen model
#     deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)
#
#     i = 0
#     for diagonal_xy in naip_sample_xy:
#
#         image_block = ImageBlock(diagonal_xy)
#         center_abs_x, center_abs_y = image_block.get_absolute_center()
#         print(f"Center {i + 1} (x, y): {center_abs_x}, {center_abs_y}")
#         tx, ty, bx, by = image_block.get_all_coordinates()
#         naip_sample_img = naip.naip_img[:, ty:by+1, tx:bx+1]
#         sample_bgr_img = util.naip_to_bgr(naip_sample_img)
#         cv2.imwrite(os.path.join(util.NAIP_RANDOM_SAMPLES_DIR, f"sample_{i + 1}.png"), sample_bgr_img)
#
#         # Get center coordinates of current sample
#         # center_lon, center_lat = naip.get_lon_lat(row=center_abs_y, col=center_abs_x)
#         center_lon, center_lat = naip.get_center_lon_lat((tx, ty), (bx, by))
#         print(f"Center Geo {i + 1}: {center_lon}, {center_lat}")
#
#         s_h, s_w = image_block.get_block_size()
#         wayback_h, wayback_w = util.get_wayback_shot_size((s_h, s_w),
#                                                           naip_resolution,
#                                                           wayback_resolution,
#                                                           beta=1.1)
#         # print(f"Wayback shot size: {wayback_h, wayback_w}")
#         driver = webdriver.Chrome(options=options)
#         wayback_driver = ImageryWaybackDriver(driver)
#
#         # Load webpage with url
#         url = wayback_driver.make_url(center_lon, center_lat, scale=wayback_scale)
#         wayback_driver.load_url(url)
#         wayback_driver.toggle_off_version_filter()
#         wayback_driver.accept_cookies()
#
#         save_wayback = os.path.join(util.WAYBACK_SCREENSHOTS_DIR, f"wayback_shot_{i + 1}.png")
#         wayback_img = wayback_driver.take_screenshot(wayback_w, wayback_h,
#                                                      save_to_file=save_wayback)
#         wayback_driver.close()
#         wayback_img = cv2.cvtColor(wayback_img, cv2.COLOR_RGB2BGR)
#
#         # Get inference from the DeepGreen model
#         ground_truth_segs = deep_green.infer_batch([wayback_img])
#
#         # Threshold the segmentation results generated by the DeepGreen model
#         _, ground_truth_seg = cv2.threshold(ground_truth_segs[0], 0, 255, cv2.THRESH_BINARY)
#         # ground_truth_seg_binary = ground_truth_seg.astype(np.bool_)
#         # np.save(os.path.join(util.GROUND_TRUTH_MASKS_BINARY_DIR,
#         #                      f"ground_truth_mask_binary_{str(i + 1).zfill(n_digits)}.npy"),
#         #         ground_truth_seg_binary)
#
#         ground_truth_gray = ground_truth_seg.astype(np.uint8)
#         ground_truth_color = NAIPImagery.set_mask_color(ground_truth_gray, (0, 0, 255))
#         combined_ground_truth = cv2.addWeighted(wayback_img, 1, ground_truth_color, 0.5, 0)
#         cv2.imwrite(os.path.join(util.GROUND_TRUTH_MASKS_DIR, f"ground_truth_mask_{str(i + 1).zfill(n_digits)}.png"),
#                     ground_truth_gray)
#         cv2.imwrite(os.path.join(util.GROUND_TRUTH_IMAGES_DIR, f"ground_truth_image_{str(i + 1).zfill(n_digits)}.png"),
#                     combined_ground_truth)
#         i += 1


def generate_naip_vegetation_masks(naip_img_path: str,
                                   coordinate_file_path: str,
                                   naip_output_mask_path: str,
                                   naip_output_land_cover_path: str | None,
                                   ndvi_threshold: float):
    naip_img = util.read_naip_image(naip_img_path)
    naip = NAIPImagery(naip_img)
    # naip_bgr_img = naip_obj.get_bgr_naip()
    sample_coordinates = np.load(coordinate_file_path)
    n_samples = sample_coordinates.shape[0]
    n_digits = len(str(n_samples))

    for i, coordinate in enumerate(sample_coordinates):
        tx, ty, bx, by = coordinate
        naip_sample = naip[:, ty:by+1, tx:bx+1]
        mask = naip_sample.generate_vegetation_mask(ndvi_threshold)
        mask[mask != 0] = 255
        out_filename = f"naip_mask_{str(i + 1).zfill(n_digits)}.png"
        out_path = os.path.join(naip_output_mask_path, out_filename)
        cv2.imwrite(out_path, mask)
        # mask_binary = mask.astype(np.bool_)
        # out_filename = f"naip_mask_binary_{str(i + 1).zfill(n_digits)}.npy"
        # out_path = os.path.join(util.NAIP_MASKS_BINARY_DIR, out_filename)
        # np.save(out_path, mask_binary)

        # naip_image = naip_bgr_img[ty:by + 1, tx:bx + 1, :]
        if naip_output_land_cover_path is not None:
            vegetation_cover = naip_sample.generate_vegetation_cover_map(ndvi_threshold)

            out_filename = f"naip_vegetation_cover_{str(i + 1).zfill(n_digits)}.png"
            out_path = os.path.join(naip_output_land_cover_path, out_filename)
            cv2.imwrite(out_path, vegetation_cover)



# def generate_ground_truth(input_dir, config_path, checkpoint_path):
#     try:
#         with os.scandir(input_dir) as entries:
#             sorted_entries = sorted(entries, key=lambda x: x.name)
#     except OSError as err:
#         print(err)
#
#     images = []
#     for i, entry in enumerate(sorted_entries):
#         if entry.is_file():
#             images.append(cv2.imread(entry.path))
#
#     deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)
#     n_digits = len(str(len(images)))
#     for i, image in enumerate(images):
#         ground_truth_seg = deep_green.infer_batch([image])[0]
#         _, ground_truth_gray = cv2.threshold(ground_truth_seg, 0, 255, cv2.THRESH_BINARY)
#         ground_truth_gray = ground_truth_gray.astype(np.uint8)
#         ground_truth_color = NAIPImagery.set_mask_color(ground_truth_gray, (0, 0, 255))
#         combined_ground_truth = cv2.addWeighted(image, 1, ground_truth_color, 0.5, 0)
#         cv2.imwrite(os.path.join("./cache/ground_truth_masks/", f"ground_truth_mask_{str(i).zfill(n_digits)}.png"), ground_truth_gray)
#         cv2.imwrite(os.path.join("./cache/ground_truth_images/", f"ground_truth_image_{str(i).zfill(n_digits)}.png"), combined_ground_truth)


def generate_grid_naip_sample(naip_path: str, output_path: str, sample_xy_filename: str):
    if not sample_xy_filename.endswith(".npy"):
        raise Exception("Output file must be of type .npy")

    naip_img = util.read_naip_image(naip_path)
    naip = NAIPImagery(naip_img)
    # naip_bgr = naip.get_bgr_naip()
    naip_h, naip_w = naip.naip_img.shape[1:]
    naip_sampler = NaipSampler(GridSample())
    naip_sample_xy = naip_sampler.get_sample_coordinates((naip_h, naip_w), (1024, 512))

    output_path = os.path.join(output_path, sample_xy_filename)
    np.save(output_path, naip_sample_xy)


def generate_ground_truth_from_rgb_naip(naip_sample_xy: numpy.ndarray,
                                        naip_path: str,
                                        config_path: str,
                                        checkpoint_path: str,
                                        output_mask_dir: str,
                                        output_image_dir: str):
    if not util.create_directory(output_mask_dir):
        util.remove_all_files(output_mask_dir)

    if not util.create_directory(output_image_dir):
        util.remove_all_files(output_image_dir)

    # Create a NAIP processor
    naip_img = util.read_naip_image(naip_path)
    naip = NAIPImagery(naip_img)

    # Initialize DeepGreen model
    deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)
    n_samples = naip_sample_xy.shape[0]
    n_digits = len(str(n_samples))

    i = 0
    for diagonal_xy in naip_sample_xy:
        print(f"Processing sample {i + 1}/{n_samples}")
        image_block = ImageBlock(diagonal_xy)
        # center_abs_x, center_abs_y = image_block.get_absolute_center()
        # print(f"Center {i + 1} (x, y): {center_abs_x}, {center_abs_y}")
        tx, ty, bx, by = image_block.get_all_coordinates()
        naip_sample = naip[:, ty:by + 1, tx:bx + 1]
        naip_sample_bgr_img = naip_sample.get_bgr_naip()

        # Get inference from the DeepGreen model
        ground_truth_segs = deep_green.infer_batch([naip_sample_bgr_img])

        # Threshold the segmentation results generated by the DeepGreen model
        _, ground_truth_seg = cv2.threshold(ground_truth_segs[0], 0, 255, cv2.THRESH_BINARY)
        # ground_truth_seg_binary = ground_truth_seg.astype(np.bool_)
        # np.save(os.path.join(util.GROUND_TRUTH_MASKS_BINARY_DIR,
        #                      f"ground_truth_mask_binary_{str(i + 1).zfill(n_digits)}.npy"),
        #         ground_truth_seg_binary)

        ground_truth_gray = ground_truth_seg.astype(np.uint8)
        ground_truth_color = NAIPImagery.set_mask_color(ground_truth_gray, (0, 0, 255))
        combined_ground_truth = cv2.addWeighted(naip_sample_bgr_img, 1, ground_truth_color, 0.5, 0)

        out_mask_path = os.path.join(output_mask_dir, f"ground_truth_mask_{str(i + 1).zfill(n_digits)}.png")
        out_image_path = os.path.join(output_image_dir, f"ground_truth_image_{str(i + 1).zfill(n_digits)}.png")
        cv2.imwrite(out_mask_path, ground_truth_gray)
        cv2.imwrite(out_image_path, combined_ground_truth)
        i += 1


def find_optimal_ndvi_by_naip(metrics_name):
    # Set model configuration path and checkpoint path
    config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    checkpoint_path = "./checkpoints/iter_1000.pth"
    naip_path = "./image/m_4111118_nw_12_060_20210813.tif"
    sample_coordinate_file_path = "./cache/naip_sample_xy.npy"

    generate_grid_naip_sample(naip_path, "./cache/", "naip_sample_xy.npy")

    naip_sample_coordinates = util.load_npy_file(sample_coordinate_file_path)
    generate_ground_truth_from_rgb_naip(naip_sample_coordinates,
                                        naip_path,
                                        config_path,
                                        checkpoint_path,
                                        "./cache/ground_truth_mask1/",
                                        "./cache/ground_truth_image1/")

    thresholds = np.arange(0, 0.4, 0.02)
    max_metric_value = 0
    cm_outfile_name = f"confusion_matrix_{metrics_name}_on_naip.json"

    naip_sample_mask_dir = "./cache/naip_sample_mask1/"
    ground_truth_mask_dir = "./cache/ground_truth_mask1/"
    util.create_directory(naip_sample_mask_dir)
    # util.create_directory(ground_truth_mask_dir)

    n_thresholds = thresholds.size
    res = np.zeros((n_thresholds, 2), dtype=np.float64)
    i = 0
    for threshold in thresholds:
        util.remove_all_files(naip_sample_mask_dir)
        generate_naip_vegetation_masks(naip_path,
                                       sample_coordinate_file_path,
                                       naip_sample_mask_dir,
                                       None,
                                       threshold)

        # util.draw_template_match_region(util.WAYBACK_SCREENSHOTS_DIR, tm_info_path)
        print(f"Current threshold: {threshold}")
        cm = util.get_confusion_matrix_on_naip(naip_sample_mask_dir, ground_truth_mask_dir)
        print(f"Current metric ({metrics_name}) value: {cm[metrics_name]}")

        res[i, 0] = threshold
        res[i, 1] = cm[metrics_name]

        if cm[metrics_name] > max_metric_value:
            print("Updating best metric value...")
            max_metric_value = cm[metrics_name]
            print(f"Best threshold so far: {threshold}")
            cm["optimal_threshold"] = threshold
            with open(f"./cache/{cm_outfile_name}", "w+") as outfile:
                outfile.write(json.dumps(cm, indent=4))
            print(f"Best metric value ({metrics_name}) so far: {cm[metrics_name]}")
        i += 1

    np.save(f"./cache/ndvi_thresholds_on_{metrics_name}.npy", res)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    # # Set model configuration path and checkpoint path
    # config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    # checkpoint_path = "./checkpoints/iter_1000.pth"
    # naip_path = "./image/m_4111118_nw_12_060_20210813.tif"
    #
    # generate_grid_naip_sample(naip_path, "./cache/", "naip_sample_xy.npy")
    #
    # sample_coordinate_file_path = "./cache/naip_sample_xy.npy"
    # naip_sample_coordinates = util.load_npy_file(sample_coordinate_file_path)
    # generate_ground_truth_from_rgb_naip(naip_sample_coordinates,
    #                                     naip_path,
    #                                     config_path,
    #                                     checkpoint_path,
    #                                     "./cache/ground_truth_mask1/",
    #                                     "./cache/ground_truth_image1/")

    # find_optimal_ndvi_by_naip("accuracy")

    config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    checkpoint_path = "./checkpoints/iter_1000.pth"
    naip_path = "./image/m_4111118_nw_12_060_20210813.tif"

    coordinate_file_path = "./cache/naip_sample_xy.npy"
    naip_best_mask_output_path = "./cache/naip_best_match/"
    naip_best_cover_output_path = "./cache/naip_best_land_cover/"
    generate_naip_vegetation_masks(naip_path,
                                   coordinate_file_path,
                                   naip_best_mask_output_path,
                                   naip_best_cover_output_path,
                                   0.14)

    # naip_obj.generate_vegetation_mask((0, 0), ())

    # create_cache()
    # clean_cache()
    # generate_sample_ground_truth(config_path, checkpoint_path, naip_img_path, wayback_scale=18)

    # naip_img = util.read_naip_image(naip_img_path)
    # naip_processor = NAIPProcessor(naip_img)
    # tm_info = naip_processor.get_template_match_info(util.NAIP_RANDOM_SAMPLES_DIR,
    #                                                  util.WAYBACK_SCREENSHOTS_DIR,
    #                                                  util.WAYBACK_SCALE_TO_RESOLUTION["18"])

    # coordinate_file_path = "./cache/naip_random_sample_coordinates.npy"
    # tm_info_path = "./cache/tm_info.npy"
    # thresholds = np.arange(0.08, 0.4, 0.02)
    # metric_name = "kappa"
    # max_metric_value = 0
    # cm_outfile_name = f"confusion_matrix_{metric_name}.json"
    # for threshold in thresholds:
    #     util.remove_all_files(util.NAIP_SAMPLE_MASKS_DIR)
    #     generate_naip_vegetation_masks(naip_path, coordinate_file_path, threshold)
    #
    #     # util.draw_template_match_region(util.WAYBACK_SCREENSHOTS_DIR, tm_info_path)
    #     print(f"Current threshold: {threshold}")
    #     cm = util.get_confusion_matrix(util.NAIP_SAMPLE_MASKS_DIR, util.GROUND_TRUTH_MASKS_DIR, tm_info_path)
    #     print(f"Current metric ({metric_name}) value: {cm[metric_name]}")
    #
    #     if cm[metric_name] > max_metric_value:
    #         print("Updating best metric value...")
    #         max_metric_value = cm[metric_name]
    #         print(f"Best threshold so far: {threshold}")
    #         with open(f"./cache/{cm_outfile_name}", "w+") as outfile:
    #             outfile.write(json.dumps(cm, indent=4))
    #         print(f"Best metric value ({metric_name}) so far: {cm[metric_name]}")

    # main(config_path, checkpoint_path, naip_img_path, n_samples_xy=(8, 10))
    #
    # img_path = "./cache/naip_split"
    # config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    # checkpoint_path = "./checkpoints/iter_1000.pth"
    # output_dir = "./cache/ground_truth_masks"
    #
    # generate_ground_truth(img_path, config_path, checkpoint_path)
    #
    # stitch_in_dir = "./cache/ground_truth_masks/"
    # stitch_out_dir = "./cache/ground_truth_stitched_mask/"
    # utility.stitch_images(stitch_in_dir, stitch_out_dir)

    # stitch_in_dir = "./cache/ground_truth_images/"
    # stitch_out_dir = "./cache/ground_truth_stitched_image/"
    # utility.stitch_images(stitch_in_dir, stitch_out_dir)

