import os
import cv2
import numpy as np
import util
import matplotlib.pyplot as plt
from morphology.filter_factory import FilterFactory
from morphology.connected_components import CV2ConnectedComponentsGenerator, ConnectedComponents
from ndvi.naip_processor import NAIPProcessor
from web_scraper.imagery_wayback_driver import ImageryWaybackDriver
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from Inferencer.deep_recognizer import DeepGreenSpaceRecognizer


def main(config_path, checkpoint_path, naip_img_path, n_samples_per_dim=3, wayback_scale=18):
    # Create a NAIP processor
    naip = NAIPProcessor(naip_img_path)
    naip_resolution = abs(naip.get_resolution()[0])
    # naip.naip_img = naip.reproject()
    naip_bgr = naip.get_bgr_naip()

    # center_r, center_c = naip.get_center()
    # center_lon, center_lat = naip.get_lon_lat(row=center_r, col=center_c)

    # Initialize Selenium driver
    options = Options()
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.binary_location = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

    # save_wayback_img = "../image/test_data/test1/wayback_img.jpg"

    # Get a screenshot of the region of interest
    naip_h, naip_w = naip_bgr.shape[:2]
    wayback_resolution = util.WAYBACK_SCALE_TO_RESOLUTION[str(wayback_scale)]

    naip_sample_xy = util.get_naip_imagery_samples(naip_h, naip_w, n_samples_per_dim)

    # Set output root directory
    out_path_base = f"./image/test_data/test5/output_naip{naip_w}X{naip_h}_waybackScale{wayback_scale}/"

    if not os.path.exists(out_path_base):
        try:
            os.makedirs(out_path_base)
            print("Directory created.")
        except OSError as error:
            print(error)

    optimal_metrics = dict()
    all_best_thresholds = []
    for i, diagonal_xy in enumerate(naip_sample_xy):
        s_h = diagonal_xy[3] - diagonal_xy[1]
        s_w = diagonal_xy[2] - diagonal_xy[0]
        center_r, center_c = diagonal_xy[1] + (s_h // 2 - 1), diagonal_xy[0] + (s_w // 2 - 1)
        print(f"Center {i + 1}: {center_r}, {center_c}")
        naip_sample_img = naip.naip_img[:, diagonal_xy[1]:diagonal_xy[3], diagonal_xy[0]:diagonal_xy[2]]  # naip.reproject("EPSG:4326")
        wayback_h, wayback_w = util.get_wayback_shot_size((s_h, s_w), naip_resolution, wayback_resolution)
        sample_bgr_img = naip.get_bgr_naip_image(naip_sample_img)
        cv2.imwrite(os.path.join(out_path_base, f"sample_{i + 1}.png"), sample_bgr_img)

        # Get center coordinates of current sample
        center_lon, center_lat = naip.get_lon_lat(row=center_r, col=center_c)
        print(f"Center Geo {i + 1}: {center_lon}, {center_lat}")

        driver = webdriver.Chrome(options=options)
        wayback_driver = ImageryWaybackDriver(driver)

        # Load webpage with url
        url = wayback_driver.make_url(center_lon, center_lat, scale=wayback_scale)
        wayback_driver.load_url(url)
        wayback_driver.toggle_off_version_filter()
        wayback_driver.accept_cookies()

        wayback_img = wayback_driver.take_screenshot(wayback_w, wayback_h,
                                                     save_to_file=f"./image/wayback_shot_{i + 1}.png")
        wayback_img = cv2.cvtColor(wayback_img, cv2.COLOR_RGB2BGR)

        # Get inference from the DeepGreen model
        deep_green = DeepGreenSpaceRecognizer(config_path, checkpoint_path)
        ground_truth_segs = deep_green.infer_batch([wayback_img])

        # Threshold the segmentation results generated by the DeepGreen model
        _, ground_truth_seg = cv2.threshold(ground_truth_segs[0], 0, 255, cv2.THRESH_BINARY)
        ground_truth_seg = ground_truth_seg.astype(np.uint8)

        # Calculate NDVI on the NAIP imagery
        sample_ndvi = NAIPProcessor.calculate_ndvi(naip_sample_img)

        # Num must be an even number
        ndvi_thresholds = util.get_ndvi_thresholds(0, 0.3, 30)
        tm_scales = util.get_template_matching_scales(naip_resolution, wayback_resolution)

        # Set template matching methods
        # methods_backup = ['cv2.TM_CCOEFF', 'cv2.TM_CCORR', 'cv2.TM_SQDIFF']

        # for method in util.TM_METHODS_STR:
        global_max = float('-inf')
        best_threshold = 0

        print(f"Processing sample {i + 1}")
        for threshold in ndvi_thresholds:
            ndvi_classified = NAIPProcessor.classify(sample_ndvi, threshold, invert=False)
            for scale in tm_scales:
                ndvi_temp = ndvi_classified.copy()
                ndvi_temp = cv2.resize(ndvi_temp,
                                       dsize=(0, 0),
                                       fx=scale,
                                       fy=scale,
                                       interpolation=cv2.INTER_CUBIC)
                similarity_res = cv2.matchTemplate(ground_truth_seg, ndvi_temp, cv2.TM_CCOEFF_NORMED)
                min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(similarity_res)

                # if "SQDIFF" in method:
                #     if min_val < global_min:
                #         global_min = min_val
                #         if method not in optimal_thresholds:
                #             optimal_thresholds[method] = [threshold]
                #         else:
                #             optimal_thresholds[method].append(threshold)
                        # optimal_metrics[method] = (
                        # threshold, min_val, min_loc, scale, ndvi_temp.shape[:2], similarity_res)
                # else:
                if max_val > global_max:
                    global_max = max_val
                    best_threshold = threshold
                    optimal_metrics[i] = (threshold, max_val, max_loc, scale, ndvi_temp.shape[:2], similarity_res, wayback_img, ground_truth_seg)
        all_best_thresholds.append(best_threshold)

    mean_threshold = np.mean(np.array(all_best_thresholds))
    print(f"All sample thresholds: {all_best_thresholds}")
    print(f"Best estimated threshold is {mean_threshold:.4f}")
    ndvi = naip.calculate_ndvi(naip.naip_img)
    classified_ndvi = NAIPProcessor.classify(ndvi, mean_threshold, invert=False)
    color_mask = NAIPProcessor.set_mask_color(classified_ndvi, (0, 0, 255))
    combined_img = cv2.addWeighted(naip_bgr, 1, color_mask, 0.5, 0)
    filename = "recogition_wayback.png"
    full_path = os.path.join(out_path_base, filename)
    cv2.imwrite(full_path, combined_img)

    for key, val in optimal_metrics.items():
        # print(f"{key}: {val[:-1]}")
        color_ground_truth = NAIPProcessor.set_mask_color(val[-1], (0, 0, 255))
        combined_ground_truth = cv2.addWeighted(val[-2], 1, color_ground_truth, 0.5, 0)
        cv2.imwrite(os.path.join(out_path_base, f"ground_truth_sample_{key + 1}.png"), combined_ground_truth)
        ground_truth_copy = combined_ground_truth.copy()
        # best_ndvi_img = NAIPProcessor.classify(ndvi, val[0], invert=False)
        # best_ndvi_img = cv2.morphologyEx(best_ndvi_img, cv2.MORPH_OPEN, open_kernel)
        # best_ndvi_img = cv2.morphologyEx(best_ndvi_img, cv2.MORPH_CLOSE, close_kernel)
        # color_mask = NAIPProcessor.set_mask_color(best_ndvi_img, (0, 0, 255))
        bottom_right = (val[2][0] + val[4][1], val[2][1] + val[4][0])
        cv2.rectangle(ground_truth_copy, val[2], bottom_right, (0, 255, 255), 3)
        filename = "Detected_point_{}.png".format(key+1)
        cv2.imwrite(os.path.join(out_path_base, filename), ground_truth_copy)

        # combined_img = cv2.addWeighted(naip_bgr, 1, color_mask, 0.5, 0)
        # filename = "recogition_wayback_{}.png".format(key)
        # full_path = os.path.join(out_path_base, filename)
        # cv2.imwrite(full_path, combined_img)


    # wayback_img_filename = f"wayback_screenshot_{wayback_h}X{wayback_w}.png"
    # cv2.imwrite(os.path.join(out_path_base, wayback_img_filename), wayback_img)
    #
    # color_ground_truth = NAIPProcessor.set_mask_color(ground_truth_seg, (0, 0, 255))
    # combined_ground_truth = cv2.addWeighted(wayback_img, 1, color_ground_truth, 0.5, 0)
    # cv2.imwrite(os.path.join(out_path_base, "ground_truth_wayback.png"), combined_ground_truth)

    # for key, val in optimal_metrics.items():
    #     print(f"{key}: {val[:-1]}")
    #     ground_truth_copy = combined_ground_truth.copy()
    #     best_ndvi_img = NAIPProcessor.classify(ndvi, val[0], invert=False)
    #     # best_ndvi_img = cv2.morphologyEx(best_ndvi_img, cv2.MORPH_OPEN, open_kernel)
    #     # best_ndvi_img = cv2.morphologyEx(best_ndvi_img, cv2.MORPH_CLOSE, close_kernel)
    #     color_mask = NAIPProcessor.set_mask_color(best_ndvi_img, (0, 0, 255))
    #     bottom_right = (val[2][0] + val[4][1], val[2][1] + val[4][0])
    #     cv2.rectangle(ground_truth_copy, val[2], bottom_right, (0, 255, 255), 3)
    #     filename = "Detected_point_{}.png".format(key)
    #     cv2.imwrite(os.path.join(out_path_base, filename), ground_truth_copy)
    #
    #     combined_img = cv2.addWeighted(naip_bgr, 1, color_mask, 0.5, 0)
    #     filename = "recogition_wayback_{}.png".format(key)
    #     full_path = os.path.join(out_path_base, filename)
    #     cv2.imwrite(full_path, combined_img)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    # Set model configuration path and checkpoint path
    config_path = "./configs/fcn_aux-hr48_256x512_80k_singlegreen.py"
    checkpoint_path = "./checkpoints/iter_1000.pth"
    naip_img_path = "./image/m_4111118_nw_12_060_20210813.tif"

    main(config_path, checkpoint_path, naip_img_path, n_samples_per_dim=2)

    # img_path = "./image/m_4111118_nw_12_060_20210813_Clip.tif"
    # naip = NAIPProcessor(img_path)
    # naip_rgb = naip.get_bgr_naip()
    # naip_reprojected = naip.reproject("EPSG:4326")
    # ndvi = NAIPProcessor.calculate_ndvi(naip_reprojected)
    # ndvi_classified = NAIPProcessor.classify(ndvi, 0.2)
    # cv2_cc_generator = CV2ConnectedComponentsGenerator(ndvi_classified, 8)
    # cc_results = cv2_cc_generator.generate()
    #
    # cc_object = ConnectedComponents(cc_results)
    # # area_stats = cc_object.summary_statistics()
    # # print(area_stats.round(2))
    # # print(cc_object.stats)
    #
    # filter_factory = FilterFactory()
    # filters = []
    # filters.append(filter_factory.get_filter("height", "<=", 50))
    # filters.append(filter_factory.get_filter("width", ">", 20))
    # cc_object_filtered = cc_object.apply_filters(filters)
    # print("Number of filtered cc:", cc_object_filtered.labels.shape)
    #
    # test_stats = cc_object_filtered.stats
    # test_count = np.sum(test_stats[:, cv2.CC_STAT_WIDTH] <= 20)
    # print("Number of cc with width <= 20:", test_count)
    #
    # test_count = np.sum(test_stats[:, cv2.CC_STAT_HEIGHT] > 50)
    # print("Number of cc with height > 50:", test_count)
    # # print(cc_object_filtered.summary_statistics().round(2))

